[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
objc2 = "0.6.3"
objc2-app-kit = "0.3.2"
objc2-foundation = "0.3.2"
objc2-quartz-core = { version = "0.3.2", features = ["objc2-core-foundation"] }
fd-lock = "4.0.4"
dispatch = "0.2.0"
